/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_FONT_FILES           14
#define MMAP_ASSETS_FONT_CHECKSUM        0x2B75

enum MMAP_ASSETS_FONT_LISTS {
    MMAP_ASSETS_FONT_BALLET_TTF = 0,        /*!< Ballet.ttf */
    MMAP_ASSETS_FONT_BLAKAHOLLOW_TTF = 1,        /*!< BlakaHollow.ttf */
    MMAP_ASSETS_FONT_BUNGEESHADE_TTF = 2,        /*!< BungeeShade.ttf */
    MMAP_ASSETS_FONT_CHERRYBOMBONE_TTF = 3,        /*!< CherryBombOne.ttf */
    MMAP_ASSETS_FONT_EWERT_TTF = 4,        /*!< Ewert.ttf */
    MMAP_ASSETS_FONT_FLEURDELEAH_TTF = 5,        /*!< FleurDeLeah.ttf */
    MMAP_ASSETS_FONT_KUMARONEOUTLINE_TTF = 6,        /*!< KumarOneOutline.ttf */
    MMAP_ASSETS_FONT_MEGRIM_TTF = 7,        /*!< Megrim.ttf */
    MMAP_ASSETS_FONT_MOLLE_TTF = 8,        /*!< Molle.ttf */
    MMAP_ASSETS_FONT_MOMOTRUSTDISPLAY_TTF = 9,        /*!< MomoTrustDisplay.ttf */
    MMAP_ASSETS_FONT_RANCHERS_TTF = 10,        /*!< Ranchers.ttf */
    MMAP_ASSETS_FONT_SENDFLOWERS_TTF = 11,        /*!< SendFlowers.ttf */
    MMAP_ASSETS_FONT_UNIFRAKTURMAGUNTIA_TTF = 12,        /*!< UnifrakturMaguntia.ttf */
    MMAP_ASSETS_FONT_YUYUSHORT_TTF = 13,        /*!< YuyuShort.ttf */
};
